# The folders below will be cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - _site
  - vendor/bundle

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  JEKYLL_ENV: production

stages:
  - build
  - deploy

build:
  image: ruby:2.7
  stage: build
  script:
    - gem install bundler
    - bundle config set deployment 'true'
    - bundle install
    - bundle exec jekyll build

deploy:
  image: renderbit/surge
  stage: deploy
  script:
    - surge _site/
