# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Nonconformist"
description: > # this means to ignore newlines until "email:"
  Hi, I'm Soham. From time to time, I blog here.

email: soham@renderbit.com
# blog logo
logo: "/assets/images/tn_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Soham Banerjee'
author: 'Soham Banerjee'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://sohambanerjee.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@nonconformism'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/nonconformism
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/TheNonconformist
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/soham2008xyz
    desc:	Follow me on Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
